<?php
/**
 * Database Code — Admin Side Decoder
 * Developer: Rikesh | Week 6 — Task 3
 *
 * This file explains every database query used on the admin side
 * of the College IT Helpdesk system. It is a REFERENCE/DOCUMENTATION
 * file — not executed in production. Run it as a standalone page
 * (admin-only) to read the decoded explanations in your browser.
 */

require_once '../includes/config.php';
requireLogin();
requireAdmin();

$pageTitle = 'Database Code Decoder';
include '../includes/header.php';
?>

<div class="container" style="max-width:900px;">
    <div class="page-header">
        <h1 class="page-title">🔍 Database Code — Admin Decoder</h1>
        <p class="page-subtitle">Plain-English explanation of every SQL query used on the admin side</p>
    </div>

    <?php

    // ═══════════════════════════════════════════════════════════════════
    // Helper: renders a decoded SQL block with explanation
    // ═══════════════════════════════════════════════════════════════════
    function decode_block($title, $sql, $explanation, $used_in = '') {
        echo '<div class="card" style="margin-bottom:20px;">';
        echo '<div class="card-header"><span class="card-title">' . htmlspecialchars($title) . '</span>';
        if ($used_in) echo '<span style="font-size:.78rem;color:var(--text-muted);">Used in: ' . htmlspecialchars($used_in) . '</span>';
        echo '</div>';
        echo '<div class="card-body">';
        // SQL block
        echo '<pre style="background:#1e293b;color:#86efac;padding:14px 18px;border-radius:8px;font-size:.82rem;overflow-x:auto;margin-bottom:14px;">' . htmlspecialchars($sql) . '</pre>';
        // Explanation
        echo '<p style="line-height:1.75;font-size:.9rem;">' . $explanation . '</p>';
        echo '</div></div>';
    }

    // ═══════════════════════════════════════════════════════════════════
    // 1. DATABASE SCHEMA OVERVIEW
    // ═══════════════════════════════════════════════════════════════════
    echo '<h2 style="margin:28px 0 12px;font-size:1.15rem;color:var(--primary);">📐 1. Database Tables</h2>';

    decode_block(
        'users table',
        "CREATE TABLE users (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    full_name   VARCHAR(100) NOT NULL,
    email       VARCHAR(150) UNIQUE NOT NULL,
    college_id  VARCHAR(20)  UNIQUE NOT NULL,
    password    VARCHAR(255) NOT NULL,
    role        ENUM('student','faculty','staff','admin') DEFAULT 'student',
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);",
        "<b>id</b> — auto-increments (1, 2, 3 …) so every user has a unique number.<br>
         <b>email / college_id</b> — both marked UNIQUE, meaning no two users can share these.<br>
         <b>password</b> — stores a bcrypt hash (never plain text). PHP's password_hash() creates it; password_verify() checks it.<br>
         <b>role ENUM</b> — only the four listed values are accepted. 'admin' users bypass normal ticket restrictions.<br>
         <b>created_at TIMESTAMP</b> — MySQL automatically fills this when the row is inserted.",
        'register.php, login.php, admin/users.php'
    );

    decode_block(
        'tickets table',
        "CREATE TABLE tickets (
    id             INT AUTO_INCREMENT PRIMARY KEY,
    ticket_number  VARCHAR(20) UNIQUE NOT NULL,   -- e.g. TKT-A1B2C3D4
    user_id        INT NOT NULL,                  -- FK → users.id
    category       ENUM('Network','Account','Software','Hardware','Other'),
    subject        VARCHAR(200) NOT NULL,
    description    TEXT NOT NULL,
    priority       ENUM('Low','Medium','High','Critical') DEFAULT 'Medium',
    status         ENUM('Pending','In Progress','Resolved','Closed') DEFAULT 'Pending',
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);",
        "<b>ticket_number</b> — a human-readable ID (TKT-XXXXXXXX) generated by generateTicketNumber() in config.php using md5(uniqid()).<br>
         <b>user_id (Foreign Key)</b> — links each ticket back to the user who submitted it. ON DELETE CASCADE means if the user is deleted, all their tickets are automatically deleted too.<br>
         <b>status ENUM</b> — the four lifecycle states. Default is 'Pending' on creation.<br>
         <b>updated_at</b> — MySQL auto-updates this column every time ANY field in the row changes. Useful for tracking 'last activity'.",
        'admin/tickets.php, ticket.php, dashboard.php'
    );

    decode_block(
        'replies table',
        "CREATE TABLE replies (
    id         INT AUTO_INCREMENT PRIMARY KEY,
    ticket_id  INT NOT NULL,   -- FK → tickets.id
    user_id    INT NOT NULL,   -- FK → users.id (who wrote the reply)
    message    TEXT NOT NULL,
    is_admin   TINYINT(1) DEFAULT 0,   -- 0 = user reply, 1 = IT support reply
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id)   REFERENCES users(id)   ON DELETE CASCADE
);",
        "<b>ticket_id (FK)</b> — every reply belongs to exactly one ticket. ON DELETE CASCADE removes all replies when a ticket is deleted.<br>
         <b>user_id (FK)</b> — records which user (or admin) wrote the reply.<br>
         <b>is_admin TINYINT(1)</b> — acts as a boolean flag. 1 = the reply came from IT support and is styled differently in the UI (blue background).<br>
         <b>TEXT message</b> — unlimited-length text (unlike VARCHAR which has a cap).",
        'ticket.php'
    );

    // ═══════════════════════════════════════════════════════════════════
    // 2. ADMIN TICKET QUERIES (tickets.php)
    // ═══════════════════════════════════════════════════════════════════
    echo '<h2 style="margin:28px 0 12px;font-size:1.15rem;color:var(--primary);">🗂️ 2. Admin Ticket Queries</h2>';

    decode_block(
        'Fetch all tickets with user info (main dashboard query)',
        "SELECT t.*, u.full_name, u.email, u.college_id
FROM tickets t
JOIN users u ON t.user_id = u.id
WHERE 1=1
  AND t.status   = 'Pending'      -- appended if filter selected
  AND t.category = 'Network'      -- appended if filter selected
  AND t.priority = 'High'         -- appended if filter selected
  AND (t.subject LIKE '%wifi%'
    OR t.ticket_number LIKE '%wifi%'
    OR u.full_name LIKE '%wifi%'
    OR u.college_id LIKE '%wifi%') -- appended if search term entered
  AND t.user_id = 3               -- appended if user filter selected
ORDER BY t.created_at DESC;",
        "<b>t.* </b> — selects all columns from tickets (id, subject, status, priority, etc.).<br>
         <b>u.full_name / u.college_id</b> — pulled from users table so we can display them without a second query.<br>
         <b>JOIN … ON t.user_id = u.id</b> — the glue between the two tables. For each ticket row, MySQL looks up the matching user row using the foreign key.<br>
         <b>WHERE 1=1</b> — safe base condition. PHP appends each filter as <code>AND …</code> only when that filter is active.<br>
         <b>LIKE '%value%'</b> — % is a wildcard. '%wifi%' matches 'wifi issue', 'no wifi', 'bad wifi connection'.<br>
         <b>ORDER BY created_at DESC</b> — newest tickets appear at the top.",
        'admin/tickets.php'
    );

    decode_block(
        'Stats COUNT queries (for stat cards)',
        "SELECT COUNT(*) AS c FROM tickets;                          -- total
SELECT COUNT(*) AS c FROM tickets WHERE status='Pending';
SELECT COUNT(*) AS c FROM tickets WHERE status='In Progress';
SELECT COUNT(*) AS c FROM tickets WHERE status='Resolved';
SELECT COUNT(*) AS c FROM tickets WHERE status='Closed';
SELECT COUNT(*) AS c FROM tickets
  WHERE priority='Critical'
    AND status NOT IN ('Resolved','Closed');  -- critical + still open",
        "<b>COUNT(*)</b> — counts every row that matches the WHERE condition. Returns a single number.<br>
         <b>AS c</b> — gives the result column the alias 'c' so PHP reads it as <code>$row['c']</code>.<br>
         <b>NOT IN ('Resolved','Closed')</b> — excludes two values at once (shorthand for <code>AND status != 'Resolved' AND status != 'Closed'</code>).<br>
         Each query runs independently and feeds one stat card on the dashboard.",
        'admin/tickets.php, dashboard.php'
    );

    decode_block(
        'Inline status update (Save button)',
        "UPDATE tickets
SET status = ?,
    updated_at = NOW()
WHERE id = ?;
-- PHP: bind_param(\"si\", \$new_status, \$ticket_id)",
        "<b>UPDATE … SET</b> — modifies specific columns without touching the rest of the row.<br>
         <b>NOW()</b> — MySQL function that inserts the current date and time into updated_at.<br>
         <b>? placeholders (prepared statement)</b> — PHP fills these in with bind_param. This prevents SQL injection: a user cannot inject SQL through the status dropdown because the value is parameterised, not concatenated.<br>
         <b>\"si\" type string</b> — tells PHP the first param is a String and the second is an Integer.",
        'admin/tickets.php'
    );

    decode_block(
        'Close ticket (Close button)',
        "UPDATE tickets
SET status = 'Closed',
    updated_at = NOW()
WHERE id = ?;
-- PHP: bind_param(\"i\", \$ticket_id)",
        "<b>Hard-coded 'Closed'</b> — the status is set directly in the SQL rather than from user input, so it's impossible for a bad actor to pass any other value.<br>
         <b>WHERE id = ?</b> — only the specific ticket the admin clicked is affected. Without this WHERE clause, every ticket in the database would be closed.",
        'admin/tickets.php'
    );

    decode_block(
        'Delete ticket (Delete button)',
        "DELETE FROM tickets WHERE id = ?;
-- PHP: bind_param(\"i\", \$ticket_id)
--
-- Cascade effect on replies table:
-- FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE
-- → All replies for this ticket are automatically deleted too.",
        "<b>DELETE FROM … WHERE id = ?</b> — removes the single ticket row identified by its primary key.<br>
         <b>ON DELETE CASCADE</b> — because the replies table has a foreign key to tickets with CASCADE, MySQL automatically deletes all replies belonging to this ticket in the same operation. No extra DELETE query needed.<br>
         <b>Why a prepared statement?</b> — ticket_id comes from a hidden form field which could be tampered with. Using <code>intval()</code> + prepared statement ensures only a valid integer is executed.",
        'admin/tickets.php'
    );

    // ═══════════════════════════════════════════════════════════════════
    // 3. USER MANAGEMENT QUERIES (users.php)
    // ═══════════════════════════════════════════════════════════════════
    echo '<h2 style="margin:28px 0 12px;font-size:1.15rem;color:var(--primary);">👥 3. User Management Queries</h2>';

    decode_block(
        'Fetch all users with ticket count (users.php)',
        "SELECT u.*,
       (SELECT COUNT(*) FROM tickets WHERE user_id = u.id) AS ticket_count
FROM users u
WHERE id != \$_SESSION['user_id']   -- exclude the logged-in admin
  AND (full_name LIKE '%search%'
    OR email     LIKE '%search%'
    OR college_id LIKE '%search%')  -- appended if search active
  AND role = 'student'              -- appended if role filter active
ORDER BY created_at DESC;",
        "<b>Correlated sub-query</b> — <code>(SELECT COUNT(*) FROM tickets WHERE user_id = u.id)</code> runs once per user row and returns how many tickets that user has submitted. This avoids a separate JOIN + GROUP BY.<br>
         <b>id != session user_id</b> — prevents the currently logged-in admin from seeing themselves in the list (admins shouldn't delete or filter themselves accidentally).<br>
         <b>Multiple LIKE conditions</b> — the search term is checked against name, email, and college ID so the admin can find users in different ways.",
        'admin/users.php'
    );

    // ═══════════════════════════════════════════════════════════════════
    // 4. AUTHENTICATION QUERIES (config.php / login.php)
    // ═══════════════════════════════════════════════════════════════════
    echo '<h2 style="margin:28px 0 12px;font-size:1.15rem;color:var(--primary);">🔐 4. Authentication Queries</h2>';

    decode_block(
        'Login query (login.php)',
        "SELECT * FROM users WHERE email = ?;
-- PHP: bind_param(\"s\", \$email)
-- Then: password_verify(\$input_password, \$row['password'])",
        "<b>Why not WHERE email=? AND password=?</b> — because passwords are stored as bcrypt hashes, not plain text. You can't match them in SQL. Instead: fetch the row by email, then call PHP's <code>password_verify()</code> which compares the plain input against the hash.<br>
         <b>SELECT *</b> — all columns are needed to populate the session (id, full_name, role, etc.).",
        'login.php'
    );

    decode_block(
        'Register query (register.php)',
        "INSERT INTO users (full_name, email, college_id, password, role)
VALUES (?, ?, ?, ?, 'student');
-- PHP: bind_param(\"ssss\", \$name, \$email, \$college_id, \$hashed_pw)
-- \$hashed_pw = password_hash(\$plain_password, PASSWORD_BCRYPT)",
        "<b>password_hash()</b> — never stores plain passwords. bcrypt adds a random salt and runs many hash iterations, making brute-force attacks extremely slow.<br>
         <b>'student' hard-coded</b> — new registrants are always students. Admin role can only be set directly in the database, preventing privilege escalation through the sign-up form.",
        'register.php'
    );

    // ═══════════════════════════════════════════════════════════════════
    // 5. REPLY QUERIES (ticket.php)
    // ═══════════════════════════════════════════════════════════════════
    echo '<h2 style="margin:28px 0 12px;font-size:1.15rem;color:var(--primary);">💬 5. Reply Queries</h2>';

    decode_block(
        'Fetch replies for a ticket',
        "SELECT r.*, u.full_name, u.role
FROM replies r
JOIN users u ON r.user_id = u.id
WHERE r.ticket_id = ?
ORDER BY r.created_at ASC;",
        "<b>ORDER BY created_at ASC</b> — oldest reply first (chronological chat order), opposite of ticket listing.<br>
         <b>u.role</b> — used by the UI to decide whether to label a reply 'IT Support 🛠️' or 'User 👤'.",
        'ticket.php'
    );

    decode_block(
        'Insert a new reply',
        "INSERT INTO replies (ticket_id, user_id, message, is_admin)
VALUES (?, ?, ?, ?);
-- PHP: bind_param(\"iisi\", \$ticket_id, \$user_id, \$message, \$is_admin)
-- \$is_admin = isAdmin() ? 1 : 0",
        "<b>is_admin flag</b> — set to 1 if the reply is from an admin; this switches the UI to the blue 'IT Support' style.<br>
         <b>Auto-status update after admin reply</b>: If the ticket is still 'Pending' when an admin replies, a second query fires:<br>
         <code>UPDATE tickets SET status='In Progress' WHERE id=\$ticket_id</code><br>
         This automatically moves the ticket forward in the workflow.",
        'ticket.php'
    );

    ?>

    <div class="card" style="margin-top:28px;background:var(--surface-2, #f0f9ff);border:1px solid var(--primary);">
        <div class="card-body" style="text-align:center;padding:20px;">
            <p style="font-weight:600;color:var(--primary);margin:0;">
                📘 This file is for reference only — it does not modify any database data.
            </p>
            <p style="font-size:.87rem;color:var(--text-muted);margin:6px 0 0;">
                Developer: Rikesh &nbsp;|&nbsp; Week 6 &nbsp;|&nbsp; Task 3: Decoding Database Code (Admin Side)
            </p>
        </div>
    </div>

</div>

<?php include '../includes/footer.php'; ?>
